WITH USER_CONFIRMATION AS (
  SELECT
    USER_ID,
    COUNT(CASE WHEN ACTION = 'confirmed' THEN USER_ID END) AS CONFIRMED_COUNT,
    COUNT(*) AS TOTAL_COUNT
  FROM SIGNUPS
  LEFT JOIN CONFIRMATIONS
  USING (USER_ID)
  GROUP BY USER_ID
)

SELECT
  USER_ID,
  ROUND(CONFIRMED_COUNT / TOTAL_COUNT, 2) AS CONFIRMATION_RATE
FROM USER_CONFIRMATION;