name: Slack Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Send custom Slack message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          COMMIT_MESSAGE="$(git log --format=%B -n 1 ${{ github.sha }})"
          COMMIT_LINK="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          FILE_NAMES=$(git diff --name-only HEAD^ HEAD)
          MESSAGE="Latest commit: \"$COMMIT_MESSAGE\"\n$COMMIT_LINK\nChanged files:\n$FILE_NAMES"
          PAYLOAD=$(echo -e "$MESSAGE" | node ${GITHUB_WORKSPACE}/slackMsg.js)
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
